#!/bin/bash
# Quick start guide untuk AnerysAI LLM
# Save as: run_quick_demo.sh
# Usage: bash run_quick_demo.sh

echo "=================================="
echo "AneryzAI LLM - Quick Start Demo"
echo "=================================="
echo ""

# Check if we're in the right directory
if [ ! -f "train.py" ]; then
    echo "Error: Please run this script from the project root directory"
    exit 1
fi

echo "Step 1: Installing dependencies..."
echo "Command: pip install -r requirements.txt"
echo ""
echo "Note: This will install:"
echo "  - PyTorch (deep learning framework)"
echo "  - NumPy (numerical computing)"
echo "  - TQDM (progress bars)"
echo ""

echo "Step 2: Training the model..."
echo ""
echo "Option A - Quick training (2 minutes, CPU):"
echo "  python train.py --embedding_dim 256 --num_layers 2 --batch_size 4 --num_epochs 1 --device cpu"
echo ""
echo "Option B - Full training (10+ minutes, GPU recommended):"
echo "  python train.py --num_epochs 3 --batch_size 32 --device cuda"
echo ""
echo "Option C - Medium training (5 minutes, CPU):"
echo "  python train.py --embedding_dim 512 --num_layers 4 --batch_size 8 --num_epochs 1 --device cpu"
echo ""

echo "Step 3: Running inference..."
echo ""
echo "Option 1 - Demo mode (shows examples):"
echo "  python inference.py --device cpu"
echo ""
echo "Option 2 - Interactive mode (input your own prompts):"
echo "  python inference.py --device cpu --interactive"
echo ""
echo "Option 3 - Batch mode (process multiple prompts):"
echo "  python inference.py --device cpu --batch"
echo ""

echo "Step 4: Running examples..."
echo ""
echo "View all 10 implementation examples:"
echo "  python examples.py"
echo ""

echo "=================================="
echo "Quick Tutorial"
echo "=================================="
echo ""
echo "1. TRAINING MODEL:"
echo "   - Tokenizer dilatih dengan Inggris dan Indonesia"
echo "   - Model Transformer dengan 110M parameters"
echo "   - Best model disimpan di checkpoints/best_model.pt"
echo ""

echo "2. GENERATING TEXT:"
echo "   - Prompt bisa dalam Inggris atau Indonesia"
echo "   - Language otomatis terdeteksi"
echo "   - Supports multiple sampling strategies"
echo ""

echo "3. INTERACTIVE MODE:"
echo "   - Type prompt dan tekan Enter"
echo "   - Commands: /en (force English), /id (force Indonesian), /config"
echo "   - Type 'quit' untuk exit"
echo ""

echo "=================================="
echo "Key Files"
echo "=================================="
echo ""
echo "Documentation:"
echo "  - README.md              - Full documentation (600+ lines)"
echo "  - ARCHITECTURE.md        - Architecture diagrams (400+ lines)"
echo "  - IMPLEMENTATION_SUMMARY.md - Summary of implementation"
echo ""

echo "Source Code:"
echo "  - src/tokenizer/base_tokenizer.py    - BPE tokenizer"
echo "  - src/model/transformer.py           - Transformer model"
echo "  - src/training/trainer.py            - Training pipeline"
echo "  - src/inference/text_generator.py    - Generation engine"
echo ""

echo "Scripts:"
echo "  - train.py       - Training script"
echo "  - inference.py   - Inference script"
echo "  - examples.py    - 10 usage examples"
echo ""

echo "=================================="
echo "Typical Workflow"
echo "=================================="
echo ""
echo "1. Install dependencies:"
echo "   $ pip install -r requirements.txt"
echo ""
echo "2. Train model (first time):"
echo "   $ python train.py --num_epochs 1 --device cpu"
echo ""
echo "3. Test with demo:"
echo "   $ python inference.py --device cpu"
echo ""
echo "4. Interactive testing:"
echo "   $ python inference.py --device cpu --interactive"
echo ""

echo "=================================="
echo "For More Information"
echo "=================================="
echo ""
echo "See README.md for:          - Complete documentation"
echo "See ARCHITECTURE.md for:     - Architecture explanation"
echo "See examples.py for:         - 10 usage examples"
echo "See IMPLEMENTATION_SUMMARY.md for: - Implementation details"
echo ""

echo "=================================="
echo "Note"
echo "=================================="
echo ""
echo "- This demo uses sample training data"
echo "- For better results, train with larger dataset"
echo "- GPU (CUDA) recommended for faster training"
echo "- CPU mode works but is slower"
echo ""

echo "Ready? Run: python train.py --device cpu --embedding_dim 256 --num_layers 2 --batch_size 4"
echo ""
